//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MYCISDBEntities : DbContext
    {
        public MYCISDBEntities()
            : base("name=MYCISDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<PUB_BASECODE> PUB_BASECODE { get; set; }
        public virtual DbSet<PUB_BRSMTZ> PUB_BRSMTZ { get; set; }
        public virtual DbSet<PUB_BRSMTZMX> PUB_BRSMTZMX { get; set; }
        public virtual DbSet<PUB_CRBDMK> PUB_CRBDMK { get; set; }
        public virtual DbSet<PUB_CYFSK> PUB_CYFSK { get; set; }
        public virtual DbSet<PUB_CYLXK> PUB_CYLXK { get; set; }
        public virtual DbSet<PUB_DQDMK> PUB_DQDMK { get; set; }
        public virtual DbSet<PUB_EJKSK> PUB_EJKSK { get; set; }
        public virtual DbSet<PUB_GJDMK> PUB_GJDMK { get; set; }
        public virtual DbSet<PUB_GWYPJBDMK> PUB_GWYPJBDMK { get; set; }
        public virtual DbSet<PUB_HSKSK> PUB_HSKSK { get; set; }
        public virtual DbSet<PUB_ICD10> PUB_ICD10 { get; set; }
        public virtual DbSet<PUB_ICD9> PUB_ICD9 { get; set; }
        public virtual DbSet<PUB_JXYFDYK> PUB_JXYFDYK { get; set; }
        public virtual DbSet<PUB_KSBQDYK> PUB_KSBQDYK { get; set; }
        public virtual DbSet<PUB_KSYFDYK> PUB_KSYFDYK { get; set; }
        public virtual DbSet<PUB_KSYFDYMXK> PUB_KSYFDYMXK { get; set; }
        public virtual DbSet<PUB_LCSFXMDYK> PUB_LCSFXMDYK { get; set; }
        public virtual DbSet<PUB_LCSFXMK> PUB_LCSFXMK { get; set; }
        public virtual DbSet<PUB_MESSAGEINFO> PUB_MESSAGEINFO { get; set; }
        public virtual DbSet<PUB_MZBRXXK> PUB_MZBRXXK { get; set; }
        public virtual DbSet<PUB_MZDMK> PUB_MZDMK { get; set; }
        public virtual DbSet<PUB_MZKSDMK> PUB_MZKSDMK { get; set; }
        public virtual DbSet<PUB_MZSFZXKSK> PUB_MZSFZXKSK { get; set; }
        public virtual DbSet<PUB_MZTSSFXMK> PUB_MZTSSFXMK { get; set; }
        public virtual DbSet<PUB_PCSJJLK> PUB_PCSJJLK { get; set; }
        public virtual DbSet<PUB_PCSJWJLBK> PUB_PCSJWJLBK { get; set; }
        public virtual DbSet<PUB_PZLXK> PUB_PZLXK { get; set; }
        public virtual DbSet<PUB_QKDJK> PUB_QKDJK { get; set; }
        public virtual DbSet<PUB_QXDMK> PUB_QXDMK { get; set; }
        public virtual DbSet<PUB_SFDXMK> PUB_SFDXMK { get; set; }
        public virtual DbSet<PUB_SFXMLBK> PUB_SFXMLBK { get; set; }
        public virtual DbSet<PUB_SFXXMK> PUB_SFXXMK { get; set; }
        public virtual DbSet<PUB_SIMPLEDICT> PUB_SIMPLEDICT { get; set; }
        public virtual DbSet<PUB_SSBWK> PUB_SSBWK { get; set; }
        public virtual DbSet<PUB_SSCBK> PUB_SSCBK { get; set; }
        public virtual DbSet<PUB_SSDJDMK> PUB_SSDJDMK { get; set; }
        public virtual DbSet<PUB_SSFJK> PUB_SSFJK { get; set; }
        public virtual DbSet<PUB_SSKSDMK> PUB_SSKSDMK { get; set; }
        public virtual DbSet<PUB_SSLB> PUB_SSLB { get; set; }
        public virtual DbSet<PUB_SSMZDYK> PUB_SSMZDYK { get; set; }
        public virtual DbSet<PUB_SSMZK> PUB_SSMZK { get; set; }
        public virtual DbSet<PUB_SSRYK> PUB_SSRYK { get; set; }
        public virtual DbSet<PUB_SSTWK> PUB_SSTWK { get; set; }
        public virtual DbSet<PUB_SSZDK> PUB_SSZDK { get; set; }
        public virtual DbSet<PUB_UNIT> PUB_UNIT { get; set; }
        public virtual DbSet<PUB_WZJBK> PUB_WZJBK { get; set; }
        public virtual DbSet<PUB_YBFLK> PUB_YBFLK { get; set; }
        public virtual DbSet<PUB_YBKSK> PUB_YBKSK { get; set; }
        public virtual DbSet<PUB_YFDMK> PUB_YFDMK { get; set; }
        public virtual DbSet<PUB_YJKSK> PUB_YJKSK { get; set; }
        public virtual DbSet<PUB_YLXMK> PUB_YLXMK { get; set; }
        public virtual DbSet<PUB_YPCDMLK> PUB_YPCDMLK { get; set; }
        public virtual DbSet<PUB_YPFLK> PUB_YPFLK { get; set; }
        public virtual DbSet<PUB_YPJXK> PUB_YPJXK { get; set; }
        public virtual DbSet<PUB_YPLCMLK> PUB_YPLCMLK { get; set; }
        public virtual DbSet<PUB_YSKSBQDYK> PUB_YSKSBQDYK { get; set; }
        public virtual DbSet<PUB_YSSSDJDYK> PUB_YSSSDJDYK { get; set; }
        public virtual DbSet<PUB_YSSSDYK> PUB_YSSSDYK { get; set; }
        public virtual DbSet<PUB_YSSSFLDYK> PUB_YSSSFLDYK { get; set; }
        public virtual DbSet<PUB_ZCBMK> PUB_ZCBMK { get; set; }
        public virtual DbSet<PUB_ZCYSSSDJDYK> PUB_ZCYSSSDJDYK { get; set; }
        public virtual DbSet<PUB_ZDDMK> PUB_ZDDMK { get; set; }
        public virtual DbSet<PUB_ZDFLK> PUB_ZDFLK { get; set; }
        public virtual DbSet<PUB_ZYBRXXK> PUB_ZYBRXXK { get; set; }
        public virtual DbSet<PUB_ZYDMK> PUB_ZYDMK { get; set; }
        public virtual DbSet<PUB_ZYSFZXKSK> PUB_ZYSFZXKSK { get; set; }
        public virtual DbSet<SYS_ADDINS> SYS_ADDINS { get; set; }
        public virtual DbSet<SYS_APPUPDATEDETAILLOG> SYS_APPUPDATEDETAILLOG { get; set; }
        public virtual DbSet<SYS_APPUPDATELOG> SYS_APPUPDATELOG { get; set; }
        public virtual DbSet<SYS_BQDMK> SYS_BQDMK { get; set; }
        public virtual DbSet<SYS_BUILDTAB> SYS_BUILDTAB { get; set; }
        public virtual DbSet<SYS_BUILDTAB_DETAIL> SYS_BUILDTAB_DETAIL { get; set; }
        public virtual DbSet<SYS_COMPUTER> SYS_COMPUTER { get; set; }
        public virtual DbSet<SYS_CONFIG> SYS_CONFIG { get; set; }
        public virtual DbSet<SYS_CONFIG_EX> SYS_CONFIG_EX { get; set; }
        public virtual DbSet<SYS_DATAOBJECT> SYS_DATAOBJECT { get; set; }
        public virtual DbSet<SYS_DATAOBJECT_FIELD> SYS_DATAOBJECT_FIELD { get; set; }
        public virtual DbSet<SYS_DEFAULT> SYS_DEFAULT { get; set; }
        public virtual DbSet<SYS_DQDMK> SYS_DQDMK { get; set; }
        public virtual DbSet<SYS_FORMIMPOWER> SYS_FORMIMPOWER { get; set; }
        public virtual DbSet<SYS_GWCJDYK> SYS_GWCJDYK { get; set; }
        public virtual DbSet<SYS_GWJSDY> SYS_GWJSDY { get; set; }
        public virtual DbSet<SYS_GZGW> SYS_GZGW { get; set; }
        public virtual DbSet<SYS_HOSPITAILEVEL> SYS_HOSPITAILEVEL { get; set; }
        public virtual DbSet<SYS_HOSPITAL> SYS_HOSPITAL { get; set; }
        public virtual DbSet<SYS_JSDMK> SYS_JSDMK { get; set; }
        public virtual DbSet<SYS_KSDMK> SYS_KSDMK { get; set; }
        public virtual DbSet<SYS_NEWS> SYS_NEWS { get; set; }
        public virtual DbSet<SYS_OREP_MB> SYS_OREP_MB { get; set; }
        public virtual DbSet<SYS_OREP_NODE> SYS_OREP_NODE { get; set; }
        public virtual DbSet<SYS_OREP_PARAHINT> SYS_OREP_PARAHINT { get; set; }
        public virtual DbSet<SYS_OREP_PARALX> SYS_OREP_PARALX { get; set; }
        public virtual DbSet<SYS_OREP_QX> SYS_OREP_QX { get; set; }
        public virtual DbSet<SYS_OREP_TEMP> SYS_OREP_TEMP { get; set; }
        public virtual DbSet<SYS_PK_COLUMN> SYS_PK_COLUMN { get; set; }
        public virtual DbSet<SYS_PRINT> SYS_PRINT { get; set; }
        public virtual DbSet<SYS_PYWBK> SYS_PYWBK { get; set; }
        public virtual DbSet<SYS_REPORTPRINT> SYS_REPORTPRINT { get; set; }
        public virtual DbSet<SYS_ROLE_ATTRIB> SYS_ROLE_ATTRIB { get; set; }
        public virtual DbSet<SYS_TESTDATATYPE> SYS_TESTDATATYPE { get; set; }
        public virtual DbSet<SYS_UPDATELOG> SYS_UPDATELOG { get; set; }
        public virtual DbSet<SYS_USER_ATTRIB> SYS_USER_ATTRIB { get; set; }
        public virtual DbSet<SYS_XTDLDMK> SYS_XTDLDMK { get; set; }
        public virtual DbSet<SYS_XTGWDYK> SYS_XTGWDYK { get; set; }
        public virtual DbSet<SYS_ZGDMK> SYS_ZGDMK { get; set; }
        public virtual DbSet<SYS_ZGDMK_TEMP> SYS_ZGDMK_TEMP { get; set; }
        public virtual DbSet<SYS_ZGGWDYK> SYS_ZGGWDYK { get; set; }
        public virtual DbSet<SYS_ZGKSBQDYK> SYS_ZGKSBQDYK { get; set; }
        public virtual DbSet<SYS_ZGQMK> SYS_ZGQMK { get; set; }
        public virtual DbSet<YG_SYXJBBLJBXX> YG_SYXJBBLJBXX { get; set; }
        public virtual DbSet<YG_SYXJBBLXX> YG_SYXJBBLXX { get; set; }
        public virtual DbSet<YG_SYXJBYB> YG_SYXJBYB { get; set; }
        public virtual DbSet<PUB_DQDMK_BAK> PUB_DQDMK_BAK { get; set; }
        public virtual DbSet<SYS_CONFIG_LOG> SYS_CONFIG_LOG { get; set; }
        public virtual DbSet<SYS_ZGDMK_bak> SYS_ZGDMK_bak { get; set; }
    }
}
