//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PUB_PCSJWJLBK
    {
        public decimal XH { get; set; }
        public string SJGUID { get; set; }
        public string WJMC { get; set; }
        public string WJMCLJ { get; set; }
        public string PCUPLJ { get; set; }
        public string CJSJ { get; set; }
        public string MEMO { get; set; }
    }
}
