//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PUB_SFDXMK
    {
        public string ID { get; set; }
        public string NAME { get; set; }
        public string PY { get; set; }
        public string WB { get; set; }
        public int XTBZ { get; set; }
        public string MZFP_ID { get; set; }
        public string MZFP_MC { get; set; }
        public string ZYFP_ID { get; set; }
        public string ZYFP_MC { get; set; }
        public string MZYB_ID { get; set; }
        public string MZYB_MC { get; set; }
        public string ZYYB_ID { get; set; }
        public string ZYYB_MC { get; set; }
        public string MZKJ_ID { get; set; }
        public string MZKJ_MC { get; set; }
        public string ZYKJ_ID { get; set; }
        public string ZYKJ_MC { get; set; }
        public string HSXM_ID { get; set; }
        public string HSXM_MC { get; set; }
        public string BAXM_ID { get; set; }
        public string BAXM_MC { get; set; }
        public int YPBZ { get; set; }
        public int TSBZ { get; set; }
        public Nullable<int> YPTJBZ { get; set; }
        public Nullable<bool> JLZT { get; set; }
        public string MEMO { get; set; }
    }
}
