//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PUB_ZYBRXXK
    {
        public decimal PATID { get; set; }
        public string BLH { get; set; }
        public string BAH { get; set; }
        public string HZXM { get; set; }
        public string PY { get; set; }
        public string WB { get; set; }
        public string DJRQ { get; set; }
        public string CZYH { get; set; }
        public string CARDNO { get; set; }
        public string CARDTYPE { get; set; }
        public string SBKH { get; set; }
        public string QTKH { get; set; }
        public string YBDM { get; set; }
        public string PZH { get; set; }
        public string SFZH { get; set; }
        public string SEX { get; set; }
        public string BIRTH { get; set; }
        public Nullable<int> HYZK { get; set; }
        public string CSD_S { get; set; }
        public string CSD_S_MC { get; set; }
        public string CSD_X { get; set; }
        public string CSD_X_MC { get; set; }
        public string LXDZ { get; set; }
        public string LXDH { get; set; }
        public string LXYB { get; set; }
        public string DWBM { get; set; }
        public string DWMC { get; set; }
        public string DWDH { get; set; }
        public string DWYB { get; set; }
        public string GJBM { get; set; }
        public string GJMC { get; set; }
        public string MZBM { get; set; }
        public string MZMC { get; set; }
        public string ZYBM { get; set; }
        public string ZYMC { get; set; }
        public bool JLZT { get; set; }
        public string CENTERID { get; set; }
        public string MEMO { get; set; }
        public string SKID { get; set; }
        public string MZYS { get; set; }
        public string DYID { get; set; }
        public string DYMC { get; set; }
        public string PZH2 { get; set; }
        public string LXDZ_S { get; set; }
        public string LXDZ_X { get; set; }
        public string UNIQUENO { get; set; }
        public Nullable<decimal> YHLJJE { get; set; }
    }
}
