//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PUB_MZTSSFXMK
    {
        public decimal IDM { get; set; }
        public string XMDM { get; set; }
        public string YBDMFL { get; set; }
        public string XSMC { get; set; }
        public decimal YHBL { get; set; }
        public decimal ZFBL { get; set; }
        public Nullable<decimal> TXBL { get; set; }
        public Nullable<decimal> SXJG { get; set; }
        public string CZYH { get; set; }
        public Nullable<int> FLDM { get; set; }
        public string FLMC { get; set; }
        public string MEMO { get; set; }
    }
}
