//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PUB_YPLCMLK
    {
        public decimal IDM { get; set; }
        public string YPMC { get; set; }
        public string XWMC { get; set; }
        public string PY { get; set; }
        public string WB { get; set; }
        public string YPJX { get; set; }
        public string GGDW { get; set; }
        public bool JLZT { get; set; }
        public string YLM { get; set; }
        public string MEMO { get; set; }
    }
}
