//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PUB_SSMZK
    {
        public string ID { get; set; }
        public string NAME { get; set; }
        public string PY { get; set; }
        public string WB { get; set; }
        public string ID2 { get; set; }
        public string DJDM { get; set; }
        public string DJMC { get; set; }
        public int LB { get; set; }
        public string MEMO { get; set; }
        public string SSZC { get; set; }
        public string CM3ID { get; set; }
        public string BWID { get; set; }
        public string QKID { get; set; }
        public string FLID { get; set; }
    }
}
