//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PUB_YBFLK
    {
        public string YBDM { get; set; }
        public string YBSM { get; set; }
        public string PY { get; set; }
        public string WB { get; set; }
        public string RQFLDM { get; set; }
        public string RQFLMC { get; set; }
        public string ZTQKDM { get; set; }
        public string ZTQKMC { get; set; }
        public string BJQKDM { get; set; }
        public string BJQKMC { get; set; }
        public string TSRYDM { get; set; }
        public string TSRYMC { get; set; }
        public string HZLB { get; set; }
        public string HZLBMC { get; set; }
        public string GWYDM { get; set; }
        public string GWYMC { get; set; }
        public string PZLX { get; set; }
        public string PZLXMC { get; set; }
        public string BRLXDM { get; set; }
        public string BRLXMC { get; set; }
        public int PZYXQ { get; set; }
        public decimal YBBL { get; set; }
        public int XTBZ { get; set; }
        public int JLZT { get; set; }
        public int ZFBZ { get; set; }
        public bool ZHBZ { get; set; }
        public string FPSM { get; set; }
        public Nullable<decimal> QFJE { get; set; }
        public int JSFS { get; set; }
        public Nullable<decimal> YZTYX { get; set; }
        public string MEMO { get; set; }
        public Nullable<int> DYFL { get; set; }
        public string DYFLSM { get; set; }
        public Nullable<int> YXJ { get; set; }
        public Nullable<int> JCTJ { get; set; }
        public string DYFYCKDM { get; set; }
        public string DYPYCKDM { get; set; }
        public string DYYFDM { get; set; }
        public string YBTYPE { get; set; }
        public string GZZTMC { get; set; }
        public string MLFL { get; set; }
        public Nullable<bool> YBXH { get; set; }
        public Nullable<int> YBJKID { get; set; }
        public Nullable<bool> HYSYBZ { get; set; }
        public string HYKDM { get; set; }
        public Nullable<int> ZZGHBZ { get; set; }
        public Nullable<int> LCYHBZ { get; set; }
        public string ZHBZJH { get; set; }
        public string PZHCDJH { get; set; }
        public Nullable<int> JSTS { get; set; }
        public Nullable<decimal> DBJESX { get; set; }
        public Nullable<int> PZLRBZ { get; set; }
    }
}
