//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PUB_BRSMTZMX
    {
        public decimal PATID { get; set; }
        public int XTLB { get; set; }
        public decimal JZXH { get; set; }
        public string JZRQ { get; set; }
        public Nullable<int> GXYLX { get; set; }
        public string GXYLXMC { get; set; }
        public Nullable<decimal> STWD { get; set; }
        public Nullable<int> SSY { get; set; }
        public Nullable<int> SZY { get; set; }
        public Nullable<decimal> KFXT { get; set; }
        public Nullable<decimal> SJXT { get; set; }
        public Nullable<decimal> CHXT { get; set; }
        public Nullable<decimal> SG { get; set; }
        public Nullable<decimal> TZ { get; set; }
        public Nullable<decimal> YW { get; set; }
        public Nullable<decimal> TW { get; set; }
        public Nullable<decimal> MB { get; set; }
        public Nullable<decimal> HX { get; set; }
        public string ZYSL { get; set; }
        public string YYSL { get; set; }
        public string MEMO { get; set; }
        public Nullable<bool> ISGXYHZ { get; set; }
        public Nullable<bool> ISSZXYYC { get; set; }
        public Nullable<bool> ISQZGXY { get; set; }
        public Nullable<bool> ISDY { get; set; }
        public Nullable<System.DateTime> XYCLSJ { get; set; }
    }
}
