//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PUB_ZDDMK
    {
        public string ID { get; set; }
        public string NAME { get; set; }
        public string PY { get; set; }
        public string WB { get; set; }
        public string XWMC { get; set; }
        public string ICD9 { get; set; }
        public string ICD10 { get; set; }
        public string YJJBDM { get; set; }
        public string YJJBMC { get; set; }
        public string YBZDDM { get; set; }
        public string YBZDMC { get; set; }
        public bool JLZT { get; set; }
        public int SYBZ { get; set; }
        public string MEMO { get; set; }
        public string NBZDDM { get; set; }
        public string NBZDMC { get; set; }
        public Nullable<bool> SQSBBZ { get; set; }
        public Nullable<bool> SHZDBZ { get; set; }
        public int ZDLB { get; set; }
        public Nullable<int> SXBZ { get; set; }
        public string ZDDL { get; set; }
        public string FLDM { get; set; }
        public string CRBDM { get; set; }
    }
}
