//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PUB_MESSAGEINFO
    {
        public decimal ID { get; set; }
        public string BRDM { get; set; }
        public Nullable<decimal> YEXH { get; set; }
        public string BRMC { get; set; }
        public string FSYSDM { get; set; }
        public string FSYSMC { get; set; }
        public string FSKSDM { get; set; }
        public string FSKSMC { get; set; }
        public string FSBQDM { get; set; }
        public string FSBQMC { get; set; }
        public string FSSJ { get; set; }
        public decimal JSYSDM { get; set; }
        public string JSYSMC { get; set; }
        public string JSKSDM { get; set; }
        public string JSKSMC { get; set; }
        public string JSBQDM { get; set; }
        public string JSBQMC { get; set; }
        public int XTLB { get; set; }
        public int XXLB { get; set; }
        public string MSGINFO { get; set; }
        public string MSGXML { get; set; }
        public int XXZT { get; set; }
        public string YDSJ { get; set; }
        public string MEMO { get; set; }
    }
}
