//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PUB_PCSJJLK
    {
        public string MAC { get; set; }
        public string IP { get; set; }
        public string HOSTNAME { get; set; }
        public string KSDM { get; set; }
        public string KSMC { get; set; }
        public string BQDM { get; set; }
        public string BQMC { get; set; }
        public int SJBZ { get; set; }
        public string SJKSSJ { get; set; }
        public string SJJSSJ { get; set; }
        public string FWDSJLJ { get; set; }
        public string BDYXLL { get; set; }
        public string FBSJSJ { get; set; }
        public string SJGUID { get; set; }
    }
}
