//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PUB_YFDMK
    {
        public string ID { get; set; }
        public string NAME { get; set; }
        public string PY { get; set; }
        public string WB { get; set; }
        public int YFBZ { get; set; }
        public string YFDM { get; set; }
        public int XTBZ { get; set; }
        public bool CYBZ { get; set; }
        public bool ZYFBZ { get; set; }
        public bool XYFBZ { get; set; }
        public bool PYBZ { get; set; }
        public bool ZYFYBZ { get; set; }
        public Nullable<bool> MZDYBZ { get; set; }
        public Nullable<bool> PCBZ { get; set; }
        public Nullable<bool> PCQYBZ { get; set; }
        public Nullable<bool> PCFYFS { get; set; }
        public Nullable<bool> PCMXBZ { get; set; }
        public Nullable<bool> PCJXCEBZ { get; set; }
        public string MEMO { get; set; }
        public string ZMLB { get; set; }
        public Nullable<bool> SFZDYJ { get; set; }
        public Nullable<bool> ZDYJFS { get; set; }
        public string ZDYJRQ { get; set; }
        public Nullable<bool> ZPSYBZ { get; set; }
        public Nullable<bool> PYFYBZ { get; set; }
        public Nullable<bool> XNYFBZ { get; set; }
    }
}
