//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PUB_MZBRXXK
    {
        public decimal PATID { get; set; }
        public string BLH { get; set; }
        public string HZXM { get; set; }
        public string WB { get; set; }
        public string PY { get; set; }
        public string CARDTYPE { get; set; }
        public string CARDNO { get; set; }
        public Nullable<bool> ZJTYPE { get; set; }
        public string ZJH { get; set; }
        public string SEX { get; set; }
        public string BIRTH { get; set; }
        public string DWBM { get; set; }
        public string DWMC { get; set; }
        public string CSD_S { get; set; }
        public string CSD_X { get; set; }
        public Nullable<bool> HYZK { get; set; }
        public string GJBM { get; set; }
        public string MZDM { get; set; }
        public string DYID { get; set; }
        public string ZCBM { get; set; }
        public string ZWBM { get; set; }
        public string ZTQK { get; set; }
        public string ZYDM { get; set; }
        public string GZDM { get; set; }
        public string EKFMXM { get; set; }
        public string LXDZ_S { get; set; }
        public string LXDZ_X { get; set; }
        public string LXDZ { get; set; }
        public string LXDH { get; set; }
        public string YZBM { get; set; }
        public string LXSJ { get; set; }
        public string EMAIL { get; set; }
        public string LXR { get; set; }
        public string YBDM { get; set; }
        public string SBH { get; set; }
        public string PZH { get; set; }
        public string ZJRQ { get; set; }
        public string CZYH { get; set; }
        public string LRRQ { get; set; }
        public bool TYBZ { get; set; }
        public string MEMO { get; set; }
    }
}
