//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PUB_SFXXMK
    {
        public string ID { get; set; }
        public string NAME { get; set; }
        public string PY { get; set; }
        public string WB { get; set; }
        public string DXMDM { get; set; }
        public int XMLB { get; set; }
        public string XMDW { get; set; }
        public string XMGG { get; set; }
        public decimal XMDJ { get; set; }
        public string XMSM { get; set; }
        public int MZYJQR { get; set; }
        public int ZYYJQR { get; set; }
        public bool YJBZ { get; set; }
        public bool MZBZ { get; set; }
        public bool ZYBZ { get; set; }
        public bool JLZT { get; set; }
        public string MEMO { get; set; }
        public Nullable<decimal> DYIDM { get; set; }
    }
}
