//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PUB_YPCDMLK
    {
        public decimal IDM { get; set; }
        public decimal GG_IDM { get; set; }
        public decimal LC_IDM { get; set; }
        public string YPLH { get; set; }
        public string YPMC { get; set; }
        public string YPDM { get; set; }
        public string PY { get; set; }
        public string WB { get; set; }
        public string YPGG { get; set; }
        public string JXDM { get; set; }
        public string FLDM { get; set; }
        public string ZXDW { get; set; }
        public string GGDW { get; set; }
        public decimal GGXS { get; set; }
        public string CJDM { get; set; }
        public string CJMC { get; set; }
        public Nullable<int> YXQ { get; set; }
        public string YKDW { get; set; }
        public decimal YKXS { get; set; }
        public decimal YLSJ { get; set; }
        public int GZBZ { get; set; }
        public int TSBZ { get; set; }
        public int PSBZ { get; set; }
        public string ZMLB { get; set; }
        public string PZWH { get; set; }
        public Nullable<int> GMPBZ { get; set; }
        public Nullable<int> BABZ { get; set; }
        public Nullable<int> QJYYBZ { get; set; }
        public Nullable<int> OTCBZ { get; set; }
        public Nullable<int> LGYPBZ { get; set; }
        public string YPSMS { get; set; }
        public string CZYH { get; set; }
        public string CZRQ { get; set; }
        public bool JLZT { get; set; }
        public string MEMO { get; set; }
        public Nullable<decimal> DYIDM { get; set; }
        public string ZYDW { get; set; }
        public Nullable<decimal> ZYXS { get; set; }
        public string MZDW { get; set; }
        public Nullable<decimal> MZXS { get; set; }
    }
}
