//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_NEWS
    {
        public string XH { get; set; }
        public string CZYH { get; set; }
        public System.DateTime LRRQ { get; set; }
        public string TITLE { get; set; }
        public string NEWS { get; set; }
        public string NEWSBLOB { get; set; }
        public System.DateTime DEADLINE { get; set; }
        public int TSXT { get; set; }
        public string TZKS { get; set; }
    }
}
