//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_HOSPITAL
    {
        public string ID { get; set; }
        public string NAME { get; set; }
        public string PY { get; set; }
        public string WB { get; set; }
        public string REGIONID1 { get; set; }
        public string REGIONID2 { get; set; }
        public string REGIONID3 { get; set; }
        public string ZIP { get; set; }
        public string ADDRESS { get; set; }
        public string TELEPHONE { get; set; }
        public string FAX { get; set; }
        public string EMAIL { get; set; }
        public string HTTP { get; set; }
        public bool JLZT { get; set; }
        public int YYJB { get; set; }
        public string YLJGDM { get; set; }
        public int BEDS { get; set; }
        public int SYZ { get; set; }
        public int ZYXZ { get; set; }
        public int FWDX { get; set; }
        public string SJYYDM { get; set; }
        public string MEMO { get; set; }
        public string YYYH { get; set; }
        public string VERSIONKEY { get; set; }
        public string VERSIONINFO { get; set; }
        public string FJMC { get; set; }
    }
}
