//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_TESTDATATYPE
    {
        public decimal u5_XH9 { get; set; }
        public Nullable<decimal> u5_XH12 { get; set; }
        public Nullable<decimal> u5_ZFBL { get; set; }
        public Nullable<decimal> u5_SYXH { get; set; }
        public Nullable<decimal> u5_SL9 { get; set; }
        public Nullable<decimal> u5_SL14_3 { get; set; }
        public Nullable<decimal> u5_SL14 { get; set; }
        public Nullable<decimal> u5_SL13 { get; set; }
        public Nullable<decimal> u5_SL10 { get; set; }
        public Nullable<decimal> u5_MONEY8 { get; set; }
        public Nullable<decimal> u5_MONEY { get; set; }
        public Nullable<decimal> u5_KL { get; set; }
        public Nullable<decimal> u5_JE18 { get; set; }
        public Nullable<decimal> u5_JE14 { get; set; }
        public Nullable<decimal> u5_JE10 { get; set; }
        public Nullable<int> u5_INT { get; set; }
        public Nullable<decimal> u5_HL { get; set; }
        public Nullable<decimal> u5_GGSL { get; set; }
        public Nullable<decimal> u5_DWXS { get; set; }
        public Nullable<bool> u5_BZ { get; set; }
        public string u5_TEXT { get; set; }
    }
}
