//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_KSDMK
    {
        public string ID { get; set; }
        public string NAME { get; set; }
        public string PY { get; set; }
        public string WB { get; set; }
        public string YYDM { get; set; }
        public string YJKS_ID { get; set; }
        public string YJKS_MC { get; set; }
        public string YBKS_ID { get; set; }
        public string YBKS_MC { get; set; }
        public string EJKS_ID { get; set; }
        public string EJKS_MC { get; set; }
        public string HSKS_ID { get; set; }
        public string HSKS_MC { get; set; }
        public Nullable<int> KSLB { get; set; }
        public Nullable<int> KSBZ { get; set; }
        public Nullable<int> EKBZ { get; set; }
        public Nullable<int> ZRYSS { get; set; }
        public Nullable<int> ZYYSS { get; set; }
        public Nullable<int> ZZYSS { get; set; }
        public Nullable<int> HSS { get; set; }
        public Nullable<int> CWS { get; set; }
        public Nullable<int> HDCWS { get; set; }
        public Nullable<int> HDS { get; set; }
        public Nullable<decimal> YJBJ { get; set; }
        public Nullable<decimal> YJTY { get; set; }
        public Nullable<bool> QRKSBZ { get; set; }
        public string YJKSPY { get; set; }
        public string YJKSWB { get; set; }
        public string EJKSPY { get; set; }
        public string EJKSWB { get; set; }
        public bool JLZT { get; set; }
        public string MEMO { get; set; }
        public Nullable<int> MJZBZ { get; set; }
    }
}
