//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_ROLE_ATTRIB
    {
        public string ROLE_CODE { get; set; }
        public string ATTRIB_CODE { get; set; }
        public string ATTRIB_NAME { get; set; }
        public string VALUE { get; set; }
        public int VALUE_TYPE { get; set; }
        public string NOTE { get; set; }
    }
}
