//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_UPDATELOG
    {
        public string SKEY { get; set; }
        public string XTDLDM { get; set; }
        public string VERSIONKEY { get; set; }
        public string SSJRQ { get; set; }
        public string SMEMO { get; set; }
        public int SJMS { get; set; }
        public int JLZT { get; set; }
    }
}
