//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_REPORTPRINT
    {
        public string WKDZ { get; set; }
        public string IPDZ { get; set; }
        public string JSJM { get; set; }
        public string REPORT_FILE { get; set; }
        public string PRINT_XH { get; set; }
        public string KSDM { get; set; }
        public string PRINT_FILE { get; set; }
        public Nullable<bool> ISDY { get; set; }
    }
}
