//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_OREP_TEMP
    {
        public decimal XH { get; set; }
        public int PARAID { get; set; }
        public string CZYH { get; set; }
        public string PARANAME { get; set; }
        public string PARALX1 { get; set; }
        public string PARALX2 { get; set; }
        public string PARAVALUE { get; set; }
    }
}
