//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_ZGDMK_TEMP
    {
        public string ZGDM { get; set; }
        public string NAME { get; set; }
        public string PY { get; set; }
        public string WB { get; set; }
        public string ROLE_ID { get; set; }
        public string ZGXB { get; set; }
        public string CSRQ { get; set; }
        public string HYZK { get; set; }
        public string SFZH { get; set; }
        public string KSDM { get; set; }
        public string BQDM { get; set; }
        public Nullable<short> ZGLB { get; set; }
        public string ZCDM { get; set; }
        public string FZBM { get; set; }
        public string PASSWD { get; set; }
        public string GWDM { get; set; }
        public string DJSJ { get; set; }
        public string SZRY { get; set; }
        public Nullable<short> YXJL { get; set; }
        public string MEMO { get; set; }
        public string YSDJSJ { get; set; }
        public string JSSJ { get; set; }
        public string YDWMC { get; set; }
        public string ZGZSHM { get; set; }
        public string ZSHM { get; set; }
        public string LXDH { get; set; }
        public Nullable<short> JLZT { get; set; }
    }
}
