//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_DEFAULT
    {
        public string XH { get; set; }
        public string TABLE_NAME { get; set; }
        public string PK_NAME { get; set; }
        public string DEF_VALUE { get; set; }
        public string MEMO { get; set; }
        public string TYPE_NAME { get; set; }
        public string TYPE_VALUE { get; set; }
    }
}
