//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_ZGDMK_bak
    {
        public string ID { get; set; }
        public string NAME { get; set; }
        public string PY { get; set; }
        public string WB { get; set; }
        public string BIRTH { get; set; }
        public string SFZH { get; set; }
        public Nullable<int> SEX { get; set; }
        public string KSDM { get; set; }
        public string KS_MC { get; set; }
        public string BQDM { get; set; }
        public string BQ_MC { get; set; }
        public string XZKS_ID { get; set; }
        public string XZKS_MC { get; set; }
        public int ZGLB { get; set; }
        public bool ISDL { get; set; }
        public string LXDZ { get; set; }
        public string LXDH { get; set; }
        public string YZBM { get; set; }
        public string LXSJ { get; set; }
        public string ZCDM { get; set; }
        public string ZCMC { get; set; }
        public string EMAIL { get; set; }
        public string ROLE_ID { get; set; }
        public string PASSWORD { get; set; }
        public string REGIST_TIME { get; set; }
        public bool JLZT { get; set; }
        public string PHONE { get; set; }
        public string MEMO { get; set; }
        public string CZRY { get; set; }
        public string MMKSRQ { get; set; }
        public string MMJSRQ { get; set; }
        public Nullable<bool> ISSD { get; set; }
        public Nullable<bool> LSYHBZ { get; set; }
    }
}
