//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_GWCJDYK
    {
        public string GWDM { get; set; }
        public string XTDLDM { get; set; }
        public string ADDINS_KEY { get; set; }
        public Nullable<bool> JLZT { get; set; }
    }
}
