//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_BUILDTAB_DETAIL
    {
        public int XH { get; set; }
        public string TABLE_NAME { get; set; }
        public string FIELD_NAME { get; set; }
        public string FIELD_TYPE { get; set; }
        public string CAPTION { get; set; }
        public string SHOWLIST { get; set; }
        public string XTDLDM { get; set; }
        public string QUERY_FIELD { get; set; }
        public string LOCK_FIELD { get; set; }
        public string DEF_VALUE { get; set; }
        public Nullable<bool> ISEDIT { get; set; }
    }
}
