//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_COMPUTER
    {
        public string XH { get; set; }
        public string WKDZ { get; set; }
        public string CZYH { get; set; }
        public string CYYXM { get; set; }
        public string KSDM { get; set; }
        public string KSMC { get; set; }
        public string BQDM { get; set; }
        public string BQMC { get; set; }
        public string DLSJ { get; set; }
        public string TCSJ { get; set; }
        public bool ZXBZ { get; set; }
        public string IPDZ { get; set; }
        public string JSJM { get; set; }
        public string DLXT { get; set; }
        public string MEMO { get; set; }
        public string LOCKTIME { get; set; }
        public string UNLOCKTIME { get; set; }
    }
}
