//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_FORMIMPOWER
    {
        public string GWDM { get; set; }
        public string ADDIN_KEY { get; set; }
        public string DLL { get; set; }
        public int CZLB { get; set; }
        public string KJLX { get; set; }
        public string KJMC { get; set; }
        public string KJBT { get; set; }
    }
}
