//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_PK_COLUMN
    {
        public string TABLE_NAME { get; set; }
        public string PK_COLUMN { get; set; }
        public decimal PK_IDENTITY_VALUE { get; set; }
        public string XTDLDM { get; set; }
        public int TABLE_LOCK { get; set; }
    }
}
