//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class YG_SYXJBYB
    {
        public decimal XH { get; set; }
        public decimal JBXXXH { get; set; }
        public string YBBH { get; set; }
        public string YBLXCODE { get; set; }
        public string YBLXMC { get; set; }
        public string YBLXQTNR { get; set; }
        public Nullable<int> YBSL { get; set; }
        public string DWCODE { get; set; }
        public string DWMCE { get; set; }
        public string CYRQ { get; set; }
        public string MEMO { get; set; }
    
        public virtual YG_SYXJBBLJBXX YG_SYXJBBLJBXX { get; set; }
    }
}
