//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class YG_SYXJBBLXX
    {
        public decimal XH { get; set; }
        public decimal JBXXXH { get; set; }
        public string SPMC { get; set; }
        public string SPPP { get; set; }
        public string SCCJ { get; set; }
        public string GMDD { get; set; }
        public string JSCS { get; set; }
        public string JSSJ { get; set; }
        public Nullable<int> JSRS { get; set; }
        public Nullable<int> QTRSFFB { get; set; }
        public Nullable<int> SFCY { get; set; }
    
        public virtual YG_SYXJBBLJBXX YG_SYXJBBLJBXX { get; set; }
    }
}
